In [9]:
## The Python Programming Language: Functions

In [10]:
def add_numbers(x,y):
    return x + y

add_numbers(5, 7)

12

In [11]:
def add_numbers(x, y, z=None):
    if z == None:
        return x + y
    else:
        return x + y + z

add_numbers(5, 7)

12

In [12]:
##The Python Programming Language: Types and Sequences

In [13]:
type('This is a string')

str

In [14]:
type(None)

NoneType

In [15]:
type(1)

int

In [16]:
type(1.0)

float

In [17]:
type(add_numbers)

function

In [18]:
x = (1, 'a', True, 'b')
type(x)

tuple

In [22]:
x = [1, 'a', True, 'b']
type(x)

list

In [23]:
x.append(3.3)
print(x)

[1, 'a', True, 'b', 3.3]


In [25]:
for item in x:
    print(item)

1
a
True
b
3.3


In [26]:
i = 0
while (i != len(x)):
    print(x[i])
    i += 1

1
a
True
b
3.3


In [27]:
1 in [1,2,3]

True

In [28]:
 x = 'This is a string'
 print(x[0])
 print(x[0:1])
 print(x[0:2])


T
T
Th


In [29]:
x[-1]

'g'

In [30]:
x[-4:-2]

'ri'

In [31]:
x[:3]

'Thi'

In [32]:
x[3:]

's is a string'

In [33]:
firstname = 'Christopher'
lastname = 'Brooks'
print(firstname + ' ' + lastname)


Christopher Brooks


In [21]:
firstname = 'Christopher Artur Hansen Brooks'.split(' ')[0]
lastname = 'Christopher Artur Hansen Brooks'.split(' ')[-1]
print(firstname, lastname)

Christopher Brooks


In [35]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}

In [36]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com


In [37]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com


In [38]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com


In [40]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [41]:
fname

'Christopher'

In [42]:
##The Python Programming Language:  Manipulation

In [43]:
print('Chris' + str(2))

Chris2


In [44]:
sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Chris'
}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(
    sales_record['person'],
    sales_record['num_items'],
    sales_record['price'],
    sales_record['num_items']*sales_record['price']
))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


In [45]:
#Data Files and Summary Statistics

In [46]:
import csv
%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg[:3]

FileNotFoundError: [Errno 2] No such file or directory: 'mpg.csv'

In [47]:
len(mpg)

NameError: name 'mpg' is not defined

In [48]:
mpg[0].keys()

NameError: name 'mpg' is not defined

In [49]:
sum(float(d['cty']) for d in mpg) / len(mpg)

NameError: name 'mpg' is not defined

In [1]:
cylinders = set(d['cyl'] for d in mpg)


NameError: name 'mpg' is not defined

In [2]:
## Python Programming Language: Python Dates and Times

In [4]:
import datetime as dt
import time as tm

In [5]:
tm.time()

1618707788.945484

In [7]:
dtnow = dt.datetime(2016, 10, 17, 10, 28, 40, 500572)
dtnow

datetime.datetime(2016, 10, 17, 10, 28, 40, 500572)

In [8]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2016, 10, 17, 10, 28, 40)

In [9]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [10]:
today = dt.date.today()

In [11]:
today-delta

datetime.date(2021, 1, 7)

In [12]:
today > today-delta

True

In [13]:
## Python Programming Language: Advanced Python Objects, map()

In [17]:
class Person:
    department = 'School of Information'

    def set_name(self, new_name):
        self.name = new_name
    
    def set_location(self, new_location):
        self.location = new_location


In [18]:
#map() function: map(function, iterable, ...)
#Return an iterator that applies function to every item of iterable, yielding the results. If additional iterable arguments are passed, function must take that many arguments and is applied to the items from all iterables in parallel. With multiple iterables, the iterator stops when the shortest iterable is exhausted. For cases where the function inputs are already arranged into argument tuples. 

In [19]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks lives in Ann Arbor, MI, USA and works in the department School of Information


In [20]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [22]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

In [25]:
def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return "{} {}".format(title,lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [26]:
##Advanced Python Lambda and List Comprehensions

In [27]:
my_function = lambda a, b, c : a + b

In [28]:
my_function(1,2,3)

3

In [29]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

In [30]:
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [31]:
my_list = []
for number in range(0,1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [32]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [43]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

In [42]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids

[]


In [1]:
#Numpy

In [3]:
import numpy as np
import math

In [5]:
#Arrays are displayed as a list or a list of lists and can be created through list as well. When creating an array, we pass in a list as an argument in numpy array.

a = np.array([1, 2, 3])
print(a)

#we can print the number of dimensions of a list using the ndim attribute
print(a.ndim)

[1 2 3]
1


In [6]:
#If we pass in a list of lists in numpy array, we create a multi-dimensional array, for instance, a matrix
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#We can print out the length of each dimension by calling the same attribute, which returns a tuple
b.shape

(2, 3)

In [8]:
#We can check the type of items in the array
a.dtype

dtype('int64')

In [10]:
c = np.array([2.2, 5, 1.1])
c

array([2.2, 5. , 1.1])

In [11]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#We can also generate an array with random numbers
np.random.rand(2,3)

array([[0.45826313, 0.73270822, 0.78700112],
       [0.78313764, 0.85653038, 0.31295669]])

In [13]:
#Let's create an array of every even number from ten (inclusive) to fifty (exclusive)
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [14]:
np.linspace(0, 2, 15) # 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [15]:
#Array Operations

In [17]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a-b
print(c)

d=a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [18]:
#example 1 - farenheit to celsius

farenheit = np.array([0, -10, -5, -15, 0])

celsius = (farenheit - 31) * (5/9)
celsius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [19]:
celsius > - 20

array([ True, False, False, False,  True])

In [20]:
celsius%2 == 0

array([False, False,  True, False, False])

In [23]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A*B)
print('-'*20)
#if you want to do matrix product, we use the "@" sign or use the dot function
print(A@B)

[[2 0]
 [0 4]]
--------------------
[[5 4]
 [3 4]]


In [24]:
# The product of two matrices is only plausible when the inner dimensions of the two matrices are the same.

A.shape

(2, 2)

In [25]:
array1 = np.array([[1,2,3], [4,5,6]])
print(array1.dtype)

array2 = np.array([[7.1,8.2,9.1], [10.4,11.2,12.3]])
print(array2.dtype)

int64
float64


In [28]:
array3 = array1 + array2
print(array3)
print(array3.dtype)
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64
79.3
18.3
8.1
13.216666666666667


In [30]:
b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
from PIL import Image
from IPython.display import display

im = Image.open('chris.tiff')
display(im)

ModuleNotFoundError: No module named 'PIL'

In [32]:
array = np.array(im)
print(array.shape)


mask = np.full(array.shape, 255)

NameError: name 'im' is not defined

In [33]:
modified_array = array-mask

modified_array = modified_array*-1

modified_array = modified_array.astype(np.uint8)

reshaped = no.reshape(modified_array, (100,400))



NameError: name 'array' is not defined

In [34]:
#Indexing, Slicing and Iterating

In [37]:
#Indexing

a = np.array([1,3,5,7])
a[2]

5

In [42]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
a[1,1]

4

In [45]:
np.array([a[0,0], a[1,1], a[2,1]])

array([1, 4, 6])

In [46]:
print(a[[0,1,2], [0,1,1]])

[1 4 6]


In [47]:
#Boolean Indexing
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [48]:
print(a[a>5])

[6]


In [49]:
#Slicing

In [51]:
a = np.array([0,1,2,3,4,5])
print(a[:3])
print(a[2:4])

[0 1 2]
[2 3]


In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [61]:
sub_array = a[:2, 1:3]
print(sub_array[0,0])
sub_array[0,0] = 50
print(sub_array[0,1])

50
3


In [63]:
#Trying Numpy with Datasets
wines = np.genfromtxt('datasets/winequality-red.csv', delimiter=';', skip_header=1)

OSError: datasets/winequality-red.csv not found.

In [64]:
wines[:,0] #to get the first column, it returns a simple list of numbers
wines[:, 0:1] #to get the first column, it returns with the original shape

wines[:, 0:3]

wines[:, -1].mean()


NameError: name 'wines' is not defined

In [ ]:
graduate_admission = np.genfromtxt('datasets/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1, names=('Serial No', 'GRE Score', 'TOEFL Score', 'CGPA'))

graduate_admission['CGPA'][0:5]

graduate_admission['CGPA'] = graduate_admission['CGPA']/10*4
graduate_admission['CGPA'][0:20]

len(graduate_admission[graduate_admission['Research'] == 1])

print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.4]['GRE_Score'].mean())

graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]

